
package Vista;

import javax.swing.JOptionPane;
import org.w3c.dom.events.EventException;

/**
 *
 * @author PC
 */
public class JFormCalculadora extends javax.swing.JFrame {
    
    int num1, num2;
    String signo;

    /**
     * Creates new form JFormCalculadora
     */
    public JFormCalculadora() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Calculadora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonDividir = new javax.swing.JButton();
        jButtonRestar = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonBorrar4 = new javax.swing.JButton();
        jButtonSiete = new javax.swing.JButton();
        jButtonOcho = new javax.swing.JButton();
        jButtonNueve = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonCuatro = new javax.swing.JButton();
        jButtonCinco = new javax.swing.JButton();
        jButtonSeis = new javax.swing.JButton();
        jButtonCero = new javax.swing.JButton();
        jButtonPunto = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonUno = new javax.swing.JButton();
        jButtonDos = new javax.swing.JButton();
        jButtonTres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jTextField1.setOpaque(true);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, 190, 41));

        jButtonDividir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDividir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDividir.setText("/");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 40, 40));

        jButtonRestar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRestar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRestar.setText("-");
        jButtonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, 40));

        jButtonMultiplicar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMultiplicar.setText("*");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 40, 40));

        jButtonBorrar4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBorrar4.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBorrar4.setText("C");
        jButtonBorrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrar4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBorrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 40));

        jButtonSiete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSiete.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSiete.setText("7");
        jButtonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSieteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 40, 40));

        jButtonOcho.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOcho.setForeground(new java.awt.Color(0, 0, 0));
        jButtonOcho.setText("8");
        jButtonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOchoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 40));

        jButtonNueve.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNueve.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNueve.setText("9");
        jButtonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNueveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));

        jButtonSuma.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSuma.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 90));

        jButtonCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuatro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuatro.setText("4");
        jButtonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuatroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 40));

        jButtonCinco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCinco.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCinco.setText("5");
        jButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, 40));

        jButtonSeis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSeis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSeis.setText("6");
        jButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeisActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 40, 40));

        jButtonCero.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCero.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCero.setText("0");
        jButtonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCeroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 40));

        jButtonPunto.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPunto.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPunto.setText(".");
        jButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 40, 40));

        jButtonIgual.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIgual.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 40, 90));

        jButtonUno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUno.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUno.setText("1");
        jButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 40));

        jButtonDos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDos.setText("2");
        jButtonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 40, 40));

        jButtonTres.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTres.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTres.setText("3");
        jButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTresActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCeroActionPerformed
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_jButtonCeroActionPerformed

    private void jButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntoActionPerformed
        jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_jButtonPuntoActionPerformed

    private void jButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnoActionPerformed
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_jButtonUnoActionPerformed

    private void jButtonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosActionPerformed
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_jButtonDosActionPerformed

    private void jButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTresActionPerformed
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_jButtonTresActionPerformed

    private void jButtonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuatroActionPerformed
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_jButtonCuatroActionPerformed

    private void jButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincoActionPerformed
       jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_jButtonCincoActionPerformed

    private void jButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeisActionPerformed
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_jButtonSeisActionPerformed

    private void jButtonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSieteActionPerformed
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_jButtonSieteActionPerformed

    private void jButtonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOchoActionPerformed
        jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_jButtonOchoActionPerformed

    private void jButtonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNueveActionPerformed
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_jButtonNueveActionPerformed

    private void jButtonBorrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrar4ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonBorrar4ActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        num1 = Integer.parseInt(jTextField1.getText());
        signo = "/";
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        num1 = Integer.parseInt(jTextField1.getText());
        signo = "*";
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarActionPerformed
        num1 = Integer.parseInt(jTextField1.getText());
        signo = "-";
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonRestarActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        num1 = Integer.parseInt(jTextField1.getText());
        signo = "+";
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        num2 = Integer.parseInt(jTextField1.getText());
        Operar();

    }//GEN-LAST:event_jButtonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar4;
    private javax.swing.JButton jButtonCero;
    private javax.swing.JButton jButtonCinco;
    private javax.swing.JButton jButtonCuatro;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonDos;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonNueve;
    private javax.swing.JButton jButtonOcho;
    private javax.swing.JButton jButtonPunto;
    private javax.swing.JButton jButtonRestar;
    private javax.swing.JButton jButtonSeis;
    private javax.swing.JButton jButtonSiete;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JButton jButtonTres;
    private javax.swing.JButton jButtonUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

public void Operar(){
    try {
                switch (signo) {
            case "+":
                jTextField1.setText(Integer.toString(num1+num2));
                break;
            case "-":
                jTextField1.setText(Integer.toString(num1-num2));
                break;
            case "*":
                jTextField1.setText(Integer.toString(num1*num2));
                break;
            case "/":
                jTextField1.setText(Integer.toString(num1/num2));
                break;
                

        }
    } catch (ArithmeticException  e) {
        JOptionPane.showMessageDialog(null, "Error "+e);
        
    }
    
}


}

